In [184]:
import numpy as np
import pandas as pd

In [185]:
df_orders = pd.read_excel('Sample - Superstore.xls', sheet_name=0)
df_people = pd.read_excel('Sample - Superstore.xls', sheet_name=1)
df_returns = pd.read_excel('Sample - Superstore.xls', sheet_name=2)

In [186]:
df_orders.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2020-138688,2020-06-12,2020-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [187]:
df_people.head()

    Regional Manager   Region
0    Sadie Pawthorne     West
1        Chuck Magee     East
2  Roxanne Rodriguez  Central
3        Fred Suzuki    South

In [188]:
df_returns.head()

  Returned        Order ID
0      Yes  CA-2018-100762
1      Yes  CA-2018-100762
2      Yes  CA-2018-100762
3      Yes  CA-2018-100762
4      Yes  CA-2018-100867

In [189]:
df_returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Returned  800 non-null    object
 1   Order ID  800 non-null    object
dtypes: object(2)
memory usage: 12.6+ KB

In [190]:
df_returns.describe()

       Returned        Order ID
count       800             800
unique        1             296
top         Yes  CA-2021-100111
freq        800              14

In [191]:
print('Duplicate entries: ', df_returns.duplicated().sum())

Duplicate entries:  504

In [192]:
df_returns.columns

Index(['Returned', 'Order ID'], dtype='object')

In [193]:
df_returns['Returned'].unique()

array(['Yes'], dtype=object)

In [194]:
df_returns['Order ID'].unique()

array(['CA-2018-100762', 'CA-2018-100867', 'CA-2018-102652',
       'CA-2018-103373', 'CA-2018-103744', 'CA-2018-103940',
       'CA-2018-104829', 'CA-2018-105270', 'CA-2018-108609',
       'CA-2018-108861', 'CA-2018-109918', 'CA-2018-110786',
       'CA-2018-111871', 'CA-2018-116785', 'CA-2018-123225',
       'CA-2018-123253', 'CA-2018-123498', 'CA-2018-124688',
       'CA-2018-126361', 'CA-2018-126403', 'CA-2018-126522',
       'CA-2018-127012', 'CA-2018-127131', 'CA-2018-133690',
       'CA-2018-134726', 'CA-2018-135657', 'CA-2018-135699',
       'CA-2018-140816', 'CA-2018-141726', 'CA-2018-142769',
       'CA-2018-143336', 'CA-2018-143840', 'CA-2018-148614',
       'CA-2018-148950', 'CA-2018-151162', 'CA-2018-152345',
       'CA-2018-153150', 'CA-2018-156349', 'CA-2018-157924',
       'CA-2018-159338', 'CA-2018-160766', 'CA-2018-160773',
       'CA-2018-164721', 'CA-2018-164861', 'CA-2018-166744',
       'CA-2018-169019', 'CA-2019-101910', 'CA-2019-103716',
       'CA-2019-104129', 'CA-2019-105158', 'CA-2019-107678',
       'CA-2019-109736', 'CA-2019-110814', 'CA-2019-111948',
       'CA-2019-112144', 'CA-2019-113628', 'CA-2019-114048',
       'CA-2019-116092', 'CA-2019-119214', 'CA-2019-119907',
       'CA-2019-123568', 'CA-2019-124058', 'CA-2019-130456',
       'CA-2019-130785', 'CA-2019-132374', 'CA-2019-132941',
       'CA-2019-134075', 'CA-2019-134201', 'CA-2019-135580',
       'CA-2019-138674', 'CA-2019-139731', 'CA-2019-140984',
       'CA-2019-141593', 'CA-2019-142601', 'CA-2019-143238',
       'CA-2019-143490', 'CA-2019-143602', 'CA-2019-144267',
       'CA-2019-146255', 'CA-2019-146262', 'CA-2019-146486',
       'CA-2019-148873', 'CA-2019-149342', 'CA-2019-149636',
       'CA-2019-149650', 'CA-2019-150770', 'CA-2019-150875',
       'CA-2019-151547', 'CA-2019-153220', 'CA-2019-154970',
       'CA-2019-155761', 'CA-2019-156440', 'CA-2019-157770',
       'CA-2019-157812', 'CA-2019-161627', 'CA-2019-162166',
       'CA-2019-164882', 'CA-2019-168480', 'CA-2019-168564',
       'CA-2019-169397', 'CA-2020-104689', 'CA-2020-105081',
       'CA-2020-105291', 'CA-2020-105585', 'CA-2020-106950',
       'CA-2020-109806', 'CA-2020-109869', 'CA-2020-111682',
       'CA-2020-112123', 'CA-2020-112340', 'CA-2020-113341',
       'CA-2020-114307', 'CA-2020-114727', 'CA-2020-115917',
       'CA-2020-116547', 'CA-2020-116736', 'CA-2020-118311',
       'CA-2020-118500', 'CA-2020-118899', 'CA-2020-120873',
       'CA-2020-123526', 'CA-2020-124527', 'CA-2020-126529',
       'CA-2020-126732', 'CA-2020-128671', 'CA-2020-130477',
       'CA-2020-130638', 'CA-2020-130680', 'CA-2020-133319',
       'CA-2020-133368', 'CA-2020-133802', 'CA-2020-134775',
       'CA-2020-134803', 'CA-2020-136483', 'CA-2020-136924',
       'CA-2020-138282', 'CA-2020-139269', 'CA-2020-142398',
       'CA-2020-145261', 'CA-2020-145492', 'CA-2020-145583',
       'CA-2020-145919', 'CA-2020-145982', 'CA-2020-147375',
       'CA-2020-148796', 'CA-2020-150077', 'CA-2020-151323',
       'CA-2020-151372', 'CA-2020-152814', 'CA-2020-157280',
       'CA-2020-159023', 'CA-2020-159212', 'CA-2020-159345',
       'CA-2020-161746', 'CA-2020-162138', 'CA-2020-162159',
       'CA-2020-165330', 'CA-2020-166275', 'CA-2020-167759',
       'CA-2020-168921', 'CA-2021-100111', 'CA-2021-101273',
       'CA-2021-101574', 'CA-2021-101700', 'CA-2021-101805',
       'CA-2021-102519', 'CA-2021-103380', 'CA-2021-107825',
       'CA-2021-108294', 'CA-2021-108931', 'CA-2021-109085',
       'CA-2021-111556', 'CA-2021-112725', 'CA-2021-112753',
       'CA-2021-112865', 'CA-2021-113670', 'CA-2021-115427',
       'CA-2021-115994', 'CA-2021-117212', 'CA-2021-117513',
       'CA-2021-117926', 'CA-2021-118122', 'CA-2021-118542',
       'CA-2021-119284', 'CA-2021-121258', 'CA-2021-121853',
       'CA-2021-122007', 'CA-2021-122504', 'CA-2021-123085',
       'CA-2021-123491', 'CA-2021-124401', 'CA-2021-127306',
       'CA-2021-128965', 'CA-2021-129707', 'CA-2021-130631',
       'CA-2021-131492', 'CA-2021-131618', 'CA-2021-131807',
       'CA-2021-131828', 'CA-2021-132346', 'CA-2021-134194',
       'CA-2021-135692', 'CA-2021-136308', 'CA-2021-136539',
       'CA-2021-136651', 'CA-2021-137085', 'CA-2021-137099',
       'CA-2021-137414', 'CA-2021-137428', 'CA-2021-138163',
       'CA-2021-140053', 'CA-2021-140151', 'CA-2021-140186',
       'CA-2021-140585', 'CA-2021-140963', 'CA-2021-141929',
       'CA-2021-142328', 'CA-2021-142342', 'CA-2021-142867',
       'CA-2021-142888', 'CA-2021-143084', 'CA-2021-144064',
       'CA-2021-145128', 'CA-2021-145772', 'CA-2021-147452',
       'CA-2021-150609', 'CA-2021-150910', 'CA-2021-152660',
       'CA-2021-153822', 'CA-2021-154074', 'CA-2021-154214',
       'CA-2021-154949', 'CA-2021-155712', 'CA-2021-156391',
       'CA-2021-156958', 'CA-2021-157196', 'CA-2021-158729',
       'CA-2021-159954', 'CA-2021-161459', 'CA-2021-161557',
       'CA-2021-161956', 'CA-2021-162015', 'CA-2021-165008',
       'CA-2021-165491', 'CA-2021-166093', 'CA-2021-166142',
       'CA-2021-166898', 'CA-2021-167003', 'CA-2021-167395',
       'CA-2021-168193', 'CA-2021-169327', 'CA-2021-169859',
       'CA-2021-169894', 'US-2018-105137', 'US-2018-138758',
       'US-2018-140452', 'US-2018-143287', 'US-2018-150574',
       'US-2018-164406', 'US-2018-164763', 'US-2019-110569',
       'US-2019-126214', 'US-2019-128090', 'US-2019-136749',
       'US-2019-136987', 'US-2019-137008', 'US-2019-160857',
       'US-2020-105578', 'US-2020-108455', 'US-2020-111528',
       'US-2020-114230', 'US-2020-114293', 'US-2020-115952',
       'US-2020-119046', 'US-2020-127425', 'US-2020-131149',
       'US-2020-135720', 'US-2020-140172', 'US-2020-144057',
       'US-2020-148957', 'US-2020-151827', 'US-2020-152051',
       'US-2020-156986', 'US-2020-157490', 'US-2021-103247',
       'US-2021-103828', 'US-2021-105046', 'US-2021-107888',
       'US-2021-109253', 'US-2021-118087', 'US-2021-123834',
       'US-2021-136679', 'US-2021-147886', 'US-2021-147998',
       'US-2021-151127', 'US-2021-155999'], dtype=object)

In [195]:
print('Unique order IDs: ', len(df_returns['Order ID'].unique()))

Unique order IDs:  296

In [196]:
df_returns.isna().sum()

Returned    0
Order ID    0
dtype: int64

In [197]:
df_returns.groupby('Order ID').agg({'Returned' : 'count'})

                Returned
Order ID
CA-2018-100762         4
CA-2018-100867         1
CA-2018-102652         4
CA-2018-103373         1
CA-2018-103744         2
...                  ...
US-2021-136679         2
US-2021-147886         7
US-2021-147998         1
US-2021-151127         1
US-2021-155999         2

[296 rows x 1 columns]

In [198]:
df_returns_cleaned = df_returns.copy()
df_returns_cleaned['Returned Count'] = df_returns_cleaned.groupby('Order ID')['Returned'].transform('count')
df_returns_cleaned.head()

  Returned        Order ID  Returned Count
0      Yes  CA-2018-100762               4
1      Yes  CA-2018-100762               4
2      Yes  CA-2018-100762               4
3      Yes  CA-2018-100762               4
4      Yes  CA-2018-100867               1

In [199]:
print('Duplicate entries: ', df_returns_cleaned.duplicated().sum())

Duplicate entries:  504

In [200]:
df_returns_cleaned = df_returns_cleaned.drop_duplicates()
df_returns_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 296 entries, 0 to 798
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Returned        296 non-null    object
 1   Order ID        296 non-null    object
 2   Returned Count  296 non-null    int64
dtypes: int64(1), object(2)
memory usage: 9.2+ KB

In [201]:
df_returns_cleaned = df_returns_cleaned.drop('Returned', axis=1)
df_returns_cleaned.head()

          Order ID  Returned Count
0   CA-2018-100762               4
4   CA-2018-100867               1
5   CA-2018-102652               4
9   CA-2018-103373               1
10  CA-2018-103744               2

In [202]:
df_returns_cleaned = df_returns_cleaned.reset_index(drop=True)
df_returns_cleaned.head()

         Order ID  Returned Count
0  CA-2018-100762               4
1  CA-2018-100867               1
2  CA-2018-102652               4
3  CA-2018-103373               1
4  CA-2018-103744               2

In [203]:
df_people.head()

    Regional Manager   Region
0    Sadie Pawthorne     West
1        Chuck Magee     East
2  Roxanne Rodriguez  Central
3        Fred Suzuki    South

In [204]:
df_people.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Regional Manager  4 non-null      object
 1   Region            4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes

In [205]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          9994 non-null   int64
 1   Order ID        9994 non-null   object
 2   Order Date      9994 non-null   datetime64[ns]
 3   Ship Date       9994 non-null   datetime64[ns]
 4   Ship Mode       9994 non-null   object
 5   Customer ID     9994 non-null   object
 6   Customer Name   9994 non-null   object
 7   Segment         9994 non-null   object
 8   Country/Region  9994 non-null   object
 9   City            9994 non-null   object
 10  State           9994 non-null   object
 11  Postal Code     9983 non-null   float64
 12  Region          9994 non-null   object
 13  Product ID      9994 non-null   object
 14  Category        9994 non-null   object
 15  Sub-Category    9994 non-null   object
 16  Product Name    9994 non-null   object
 17  Sales           9994 non-null   float64
 18  Quantity        9994 non-null   int64
 19  Discount        9994 non-null   float64
 20  Profit          9994 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(2), object(13)
memory usage: 1.6+ MB

In [206]:
df_orders.isna().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country/Region     0
City               0
State              0
Postal Code       11
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
dtype: int64

In [207]:
print('No. of Duplicate Rows: ', df_orders.duplicated().sum())

No. of Duplicate Rows:  0

In [208]:
df_orders.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2020-138688,2020-06-12,2020-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [209]:
df_orders_1 = df_orders.copy()
df_orders_1 = df_orders_1.drop('Row ID', axis=1)
df_orders_1 = df_orders_1.reset_index(drop=True)
df_orders_1.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2020-138688,2020-06-12,2020-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [210]:
print('No. of Duplicate Rows: ', df_orders_1.duplicated().sum())

No. of Duplicate Rows:  1

In [211]:
df_orders_1 = df_orders_1.drop_duplicates()
df_orders_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9993 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        9993 non-null   object
 1   Order Date      9993 non-null   datetime64[ns]
 2   Ship Date       9993 non-null   datetime64[ns]
 3   Ship Mode       9993 non-null   object
 4   Customer ID     9993 non-null   object
 5   Customer Name   9993 non-null   object
 6   Segment         9993 non-null   object
 7   Country/Region  9993 non-null   object
 8   City            9993 non-null   object
 9   State           9993 non-null   object
 10  Postal Code     9982 non-null   float64
 11  Region          9993 non-null   object
 12  Product ID      9993 non-null   object
 13  Category        9993 non-null   object
 14  Sub-Category    9993 non-null   object
 15  Product Name    9993 non-null   object
 16  Sales           9993 non-null   float64
 17  Quantity        9993 non-null   int64
 18  Discount        9993 non-null   float64
 19  Profit          9993 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(13)
memory usage: 1.6+ MB

In [212]:
df_orders_1.isna().sum()

Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country/Region     0
City               0
State              0
Postal Code       11
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
dtype: int64

In [213]:
#display all rows with postal code is null
df_orders_1[df_orders_1['Postal Code'].isnull()]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2234,CA-2021-104066,2021-12-05,2021-12-10,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03,7,0.0,67.6599
5274,CA-2019-162887,2019-11-07,2019-11-09,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,NaN,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20,3,0.0,178.8000
8798,US-2020-150140,2020-04-06,2020-04-10,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,NaN,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75,5,0.0,336.6350
9146,US-2020-165505,2020-01-23,2020-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98,2,0.0,42.9914
9147,US-2020-165505,2020-01-23,2020-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04,6,0.0,2.7336
9148,US-2020-165505,2020-01-23,2020-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29,13,0.0,406.7154
9386,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92,4,0.0,37.5624
9387,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28,1,0.0,5.7716
9388,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94,3,0.0,152.0232
9389,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04,1,0.0,0.9588
9741,CA-2019-117086,2019-11-08,2019-11-12,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90,5,0.0,1013.1270

In [214]:
df_orders_1[['City', 'State', 'Postal Code']].sort_values(by='City', ascending=False).head(50)
#observation is that 1 city is associated with 1 postal code

            City           State  Postal Code
7279        Yuma         Arizona      85364.0
7281        Yuma         Arizona      85364.0
4822        Yuma         Arizona      85364.0
8087        Yuma         Arizona      85364.0
3347     Yucaipa      California      92399.0
2145        York    Pennsylvania      17403.0
2146        York    Pennsylvania      17403.0
2147        York    Pennsylvania      17403.0
8475        York    Pennsylvania      17403.0
8474        York    Pennsylvania      17403.0
8500     Yonkers        New York      10701.0
3862     Yonkers        New York      10701.0
1082     Yonkers        New York      10701.0
3699     Yonkers        New York      10701.0
1084     Yonkers        New York      10701.0
1085     Yonkers        New York      10701.0
5268     Yonkers        New York      10701.0
5296     Yonkers        New York      10701.0
5297     Yonkers        New York      10701.0
3861     Yonkers        New York      10701.0
1083     Yonkers        New York      10701.0
8499     Yonkers        New York      10701.0
8498     Yonkers        New York      10701.0
8496     Yonkers        New York      10701.0
8497     Yonkers        New York      10701.0
3989  Woonsocket    Rhode Island       2895.0
5182  Woonsocket    Rhode Island       2895.0
5181  Woonsocket    Rhode Island       2895.0
5092  Woonsocket    Rhode Island       2895.0
9882   Woodstock         Georgia      30188.0
9881   Woodstock         Georgia      30188.0
2571   Woodstock        Illinois      60098.0
2882   Woodstock        Illinois      60098.0
2844   Woodstock        Illinois      60098.0
9612    Woodland      California      95695.0
3188    Woodland      California      95695.0
3189    Woodland      California      95695.0
5348    Woodbury       Minnesota      55125.0
8736    Woodbury       Minnesota      55125.0
5349    Woodbury       Minnesota      55125.0
9134      Wilson  North Carolina      27893.0
9136      Wilson  North Carolina      27893.0
6629      Wilson  North Carolina      27893.0
6701      Wilson  North Carolina      27893.0
6702      Wilson  North Carolina      27893.0
9135      Wilson  North Carolina      27893.0
121   Wilmington        Delaware      19805.0
120   Wilmington        Delaware      19805.0
1323  Wilmington  North Carolina      28403.0
119   Wilmington        Delaware      19805.0

In [215]:
df_orders_temp = df_orders_1[df_orders_1['City'].isin(['Burlington'])]
df_orders_temp[df_orders_temp['State'].isin(['Vermont'])]
#observation: in the current data we are not able to find information to impute missing Postal code

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2234,CA-2021-104066,2021-12-05,2021-12-10,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03,7,0.0,67.6599
5274,CA-2019-162887,2019-11-07,2019-11-09,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,NaN,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20,3,0.0,178.8000
8798,US-2020-150140,2020-04-06,2020-04-10,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,NaN,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75,5,0.0,336.6350
9146,US-2020-165505,2020-01-23,2020-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98,2,0.0,42.9914
9147,US-2020-165505,2020-01-23,2020-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04,6,0.0,2.7336
9148,US-2020-165505,2020-01-23,2020-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29,13,0.0,406.7154
9386,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92,4,0.0,37.5624
9387,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28,1,0.0,5.7716
9388,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94,3,0.0,152.0232
9389,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04,1,0.0,0.9588
9741,CA-2019-117086,2019-11-08,2019-11-12,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90,5,0.0,1013.1270

In [216]:
df_orders_1['Postal Code'] = df_orders_1['Postal Code'].fillna(0)
df_orders_temp = df_orders_1[df_orders_1['City'].isin(['Burlington'])]
df_orders_temp[df_orders_temp['State'].isin(['Vermont'])]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2234,CA-2021-104066,2021-12-05,2021-12-10,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,0.0,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03,7,0.0,67.6599
5274,CA-2019-162887,2019-11-07,2019-11-09,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,0.0,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20,3,0.0,178.8000
8798,US-2020-150140,2020-04-06,2020-04-10,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,0.0,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75,5,0.0,336.6350
9146,US-2020-165505,2020-01-23,2020-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,0.0,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98,2,0.0,42.9914
9147,US-2020-165505,2020-01-23,2020-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,0.0,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04,6,0.0,2.7336
9148,US-2020-165505,2020-01-23,2020-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,0.0,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29,13,0.0,406.7154
9386,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,0.0,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92,4,0.0,37.5624
9387,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,0.0,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28,1,0.0,5.7716
9388,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,0.0,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94,3,0.0,152.0232
9389,US-2021-127292,2021-01-19,2021-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,0.0,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04,1,0.0,0.9588
9741,CA-2019-117086,2019-11-08,2019-11-12,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,0.0,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90,5,0.0,1013.1270

In [217]:
df_orders_1.describe()

,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9993,9993,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000
mean,2020-04-30 01:53:24.443110144,2020-05-04 00:53:19.039327488,55185.623436,229.852846,3.789753,0.156188,28.660971
min,2018-01-03 00:00:00,2018-01-07 00:00:00,0.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2019-05-23 00:00:00,2019-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.731000
50%,2020-06-26 00:00:00,2020-06-29 00:00:00,56560.000000,54.480000,3.000000,0.200000,8.671000
75%,2021-05-14 00:00:00,2021-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,2021-12-30 00:00:00,2022-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,NaN,NaN,32074.817879,623.276074,2.225149,0.206457,234.271476

In [218]:
df_orders_1[df_orders_1['Order Date'] > df_orders_1['Ship Date']]

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country/Region, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

In [219]:
df_orders_1[df_orders_1['Order Date'] < df_orders_1['Ship Date']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 9474 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        9474 non-null   object
 1   Order Date      9474 non-null   datetime64[ns]
 2   Ship Date       9474 non-null   datetime64[ns]
 3   Ship Mode       9474 non-null   object
 4   Customer ID     9474 non-null   object
 5   Customer Name   9474 non-null   object
 6   Segment         9474 non-null   object
 7   Country/Region  9474 non-null   object
 8   City            9474 non-null   object
 9   State           9474 non-null   object
 10  Postal Code     9474 non-null   float64
 11  Region          9474 non-null   object
 12  Product ID      9474 non-null   object
 13  Category        9474 non-null   object
 14  Sub-Category    9474 non-null   object
 15  Product Name    9474 non-null   object
 16  Sales           9474 non-null   float64
 17  Quantity        9474 non-null   int64
 18  Discount        9474 non-null   float64
 19  Profit          9474 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(13)
memory usage: 1.5+ MB

In [220]:
#unique values in every column
for col in df_orders_1.columns:
    print(col, ':', df_orders_1[col].unique())

Order ID : ['CA-2020-152156' 'CA-2020-138688' 'US-2019-108966' ... 'CA-2018-110422'
 'CA-2021-121258' 'CA-2021-119914']
Order Date : <DatetimeArray>
['2020-11-08 00:00:00', '2020-06-12 00:00:00', '2019-10-11 00:00:00',
 '2018-06-09 00:00:00', '2021-04-15 00:00:00', '2020-12-05 00:00:00',
 '2019-11-22 00:00:00', '2018-11-11 00:00:00', '2018-05-13 00:00:00',
 '2018-08-27 00:00:00',
 ...
 '2020-10-11 00:00:00', '2018-06-18 00:00:00', '2021-02-28 00:00:00',
 '2019-05-09 00:00:00', '2018-11-06 00:00:00', '2019-12-29 00:00:00',
 '2018-04-03 00:00:00', '2020-06-03 00:00:00', '2019-04-12 00:00:00',
 '2018-01-21 00:00:00']
Length: 1236, dtype: datetime64[ns]
Ship Date : <DatetimeArray>
['2020-11-11 00:00:00', '2020-06-16 00:00:00', '2019-10-18 00:00:00',
 '2018-06-14 00:00:00', '2021-04-20 00:00:00', '2020-12-10 00:00:00',
 '2019-11-26 00:00:00', '2018-11-18 00:00:00', '2018-05-15 00:00:00',
 '2018-09-01 00:00:00',
 ...
 '2021-04-06 00:00:00', '2019-05-13 00:00:00', '2018-08-19 00:00:00',
 '2021-01-20 00:00:00', '2019-03-28 00:00:00', '2020-08-25 00:00:00',
 '2018-01-27 00:00:00', '2019-05-23 00:00:00', '2018-01-23 00:00:00',
 '2021-03-03 00:00:00']
Length: 1334, dtype: datetime64[ns]
Ship Mode : ['Second Class' 'Standard Class' 'First Class' 'Same Day']
Customer ID : ['CG-12520' 'DV-13045' 'SO-20335' 'BH-11710' 'AA-10480' 'IM-15070'
 'HP-14815' 'PK-19075' 'AG-10270' 'ZD-21925' 'KB-16585' 'SF-20065'
 'EB-13870' 'EH-13945' 'TB-21520' 'MA-17560' 'GH-14485' 'SN-20710'
 'LC-16930' 'RA-19885' 'ES-14080' 'ON-18715' 'PO-18865' 'LH-16900'
 'DP-13000' 'JM-15265' 'TB-21055' 'KM-16720' 'PS-18970' 'BS-11590'
 'KD-16270' 'HM-14980' 'JE-15745' 'KB-16600' 'SC-20770' 'DN-13690'
 'JC-16105' 'CS-12400' 'PG-18895' 'GM-14455' 'JS-15685' 'KB-16315'
 'RB-19705' 'PN-18775' 'KD-16345' 'ER-13855' 'RB-19465' 'GZ-14470'
 'LC-16870' 'JM-15250' 'PA-19060' 'CV-12805' 'CL-12565' 'RC-19960'
 'DK-13090' 'GG-14650' 'SC-20725' 'AD-10180' 'PF-19165' 'TS-21610'
 'LS-16975' 'DW-13585' 'LC-16885' 'JD-15895' 'SH-19975' 'SG-20080'
 'HA-14920' 'MG-17680' 'JE-16165' 'TW-21025' 'SP-20650' 'NK-18490'
 'DB-13060' 'NP-18670' 'TT-21070' 'EM-13960' 'RD-19900' 'MJ-17740'
 'BM-11140' 'CS-12130' 'JB-15400' 'SJ-20500' 'JK-15640' 'DK-13150'
 'RM-19675' 'SK-19990' 'FM-14290' 'AM-10360' 'MP-17470' 'MZ-17515'
 'CB-12025' 'VM-21685' 'FH-14365' 'MB-17305' 'BS-11755' 'LC-17140'
 'HK-14890' 'LE-16810' 'JH-15985' 'MS-17980' 'VW-21775' 'JH-15910'
 'JB-15925' 'DS-13180' 'VD-21670' 'EA-14035' 'DB-13120' 'KL-16645'
 'DW-13480' 'LH-17155' 'KC-16540' 'DL-13315' 'DR-12880' 'CC-12670'
 'Dl-13600' 'SB-20290' 'RC-19825' 'AH-10210' 'CB-12535' 'CA-12310'
 'KH-16690' 'BB-10990' 'AG-10495' 'JO-15280' 'AH-10195' 'NZ-18565'
 'KL-16555' 'AS-10225' 'CR-12625' 'SH-20395' 'BP-11185' 'TS-21205'
 'AG-10525' 'SP-20860' 'NM-18445' 'FA-14230' 'GK-14620' 'DJ-13510'
 'PO-18850' 'JL-15850' 'DB-13615' 'AC-10420' 'CC-12550' 'TD-20995'
 'AB-10060' 'JL-15505' 'VB-21745' 'KW-16435' 'JD-16060' 'MK-17905'
 'GT-14755' 'AG-10900' 'MM-18280' 'AR-10405' 'RA-19915' 'AS-10285'
 'LA-16780' 'DO-13435' 'DK-13225' 'NG-18430' 'MV-18190' 'JG-15115'
 'BP-11095' 'VP-21730' 'SS-20140' 'AG-10675' 'LF-17185' 'RF-19840'
 'KH-16510' 'KC-16675' 'CJ-12010' 'PB-19150' 'MP-17965' 'NF-18385'
 'SD-20485' 'KH-16630' 'RB-19795' 'MK-18160' 'PO-19180' 'BB-11545'
 'TB-21595' 'RB-19360' 'EB-13705' 'SC-20095' 'TN-21040' 'JS-15940'
 'MH-17785' 'JP-15520' 'JE-15475' 'JG-15805' 'XP-21865' 'EM-14065'
 'MT-18070' 'SA-20830' 'CW-11905' 'AJ-10960' 'SS-20590' 'RO-19780'
 'MD-17350' 'MY-17380' 'CM-12385' 'LS-17245' 'BN-11515' 'DB-13210'
 'MC-17605' 'BD-11605' 'PH-18790' 'MG-18145' 'KB-16240' 'JC-15340'
 'RL-19615' 'AA-10375' 'EP-13915' 'DK-12985' 'BD-11500' 'LM-17065'
 'AS-10135' 'BD-11320' 'GT-14710' 'AJ-10945' 'OT-18730' 'LP-17080'
 'CA-12775' 'JF-15490' 'FP-14320' 'EB-13840' 'JF-15415' 'SF-20200'
 'TG-21640' 'CS-11950' 'CC-12145' 'DV-13465' 'BD-11725' 'ZC-21910'
 'MS-17830' 'LR-16915' 'TP-21130' 'CK-12205' 'AS-10240' 'AR-10510'
 'NB-18655' 'GD-14590' 'CK-12595' 'NG-18355' 'CA-12265' 'SF-20965'
 'MO-17800' 'AT-10735' 'FM-14380' 'DJ-13420' 'ME-17725' 'JD-16150'
 'JL-15835' 'SC-20305' 'CC-12430' 'AR-10825' 'SR-20740' 'CR-12730'
 'EH-14125' 'SP-20545' 'TH-21235' 'RP-19390' 'RB-19570' 'CD-11980'
 'DJ-13630' 'GT-14635' 'MC-17845' 'RA-19285' 'NP-18325' 'AB-10165'
 'JO-15550' 'JK-15370' 'BN-11470' 'DP-13165' 'TH-21550' 'AP-10915'
 'RS-19765' 'SV-20365' 'CK-12325' 'RD-19810' 'MR-17545' 'SC-20695'
 'JF-15355' 'EG-13900' 'DS-13030' 'PO-19195' 'SS-20875' 'PB-19105'
 'RF-19735' 'YC-21895' 'DC-13285' 'CP-12340' 'BF-11020' 'LH-17020'
 'CS-12250' 'AJ-10795' 'BV-11245' 'DL-12865' 'BM-11785' 'LT-17110'
 'JK-15730' 'ES-14020' 'RH-19495' 'CD-11920' 'HW-14935' 'MC-18130'
 'GM-14440' 'PJ-19015' 'BW-11110' 'TR-21325' 'PG-18820' 'JL-15175'
 'BM-11650' 'EM-14095' 'AF-10885' 'GA-14725' 'CK-12760' 'DP-13105'
 'BK-11260' 'SJ-20125' 'CM-12445' 'AJ-10780' 'LS-16945' 'GP-14740'
 'PK-18910' 'SM-20005' 'AG-10765' 'PM-19135' 'LL-16840' 'JS-15595'
 'EL-13735' 'PC-18745' 'HL-15040' 'MS-17365' 'GB-14530' 'JR-16210'
 'BE-11335' 'SC-20050' 'RW-19630' 'SE-20110' 'AH-10075' 'JM-15535'
 'JJ-15760' 'RK-19300' 'CG-12040' 'RP-19270' 'KC-16255' 'KH-16360'
 'GH-14665' 'SW-20275' 'JA-15970' 'DL-12925' 'LW-16990' 'TB-21190'
 'BS-11800' 'RW-19690' 'TZ-21580' 'AS-10630' 'TS-21340' 'SL-20155'
 'MW-18235' 'RD-19585' 'RA-19945' 'MT-17815' 'VG-21790' 'JS-15880'
 'KM-16225' 'HR-14770' 'DE-13255' 'AG-10390' 'JJ-15445' 'JH-15430'
 'RD-19660' 'MO-17500' 'NS-18640' 'DG-13300' 'NF-18595' 'MG-17650'
 'TS-21160' 'BD-11620' 'CM-12160' 'SN-20560' 'EH-14005' 'FO-14305'
 'MS-17710' 'CC-12100' 'DW-13540' 'BT-11395' 'CY-12745' 'BT-11485'
 'PS-19045' 'PV-18985' 'NM-18520' 'DL-13495' 'CS-12355' 'FH-14275'
 'NC-18340' 'AA-10315' 'LT-16765' 'AP-10720' 'PM-18940' 'AT-10435'
 'CA-12055' 'HR-14830' 'BT-11530' 'LH-16750' 'SW-20755' 'SP-20620'
 'BF-11170' 'KT-16480' 'BG-11695' 'GM-14680' 'EJ-14155' 'NP-18700'
 'MH-18115' 'JR-15700' 'SM-20950' 'CC-12220' 'PF-19225' 'DC-12850'
 'BD-11770' 'GM-14500' 'TB-21355' 'JH-16180' 'EB-13975' 'QJ-19255'
 'TC-21535' 'CS-12460' 'HG-14965' 'LW-16825' 'MC-17575' 'LP-17095'
 'EB-14170' 'GZ-14545' 'CP-12085' 'FG-14260' 'LD-17005' 'AB-10255'
 'MN-17935' 'JR-15670' 'JF-15190' 'CM-12115' 'AS-10045' 'BP-11290'
 'ND-18370' 'LB-16735' 'KT-16465' 'HM-14860' 'AB-10600' 'SZ-20035'
 'MG-17890' 'JK-16120' 'PP-18955' 'YS-21880' 'KM-16375' 'AB-10105'
 'HA-14905' 'BT-11305' 'SV-20815' 'RW-19540' 'DK-12835' 'ST-20530'
 'MM-17920' 'PW-19030' 'SC-20440' 'TS-21085' 'MC-17425' 'ME-17320'
 'NH-18610' 'MB-18085' 'KD-16495' 'KN-16390' 'NP-18685' 'CS-12505'
 'MS-17770' 'CM-12655' 'Co-12640' 'TS-21370' 'JW-15220' 'JD-15790'
 'PC-19000' 'AR-10540' 'AI-10855' 'TB-21400' 'PL-18925' 'GH-14425'
 'MP-18175' 'JM-15655' 'CL-11890' 'DB-13270' 'IG-15085' 'BO-11425'
 'AB-10150' 'JW-16075' 'EB-13750' 'SG-20470' 'CM-12190' 'AW-10840'
 'MC-18100' 'TT-21460' 'VG-21805' 'MY-18295' 'RD-19480' 'DP-13390'
 'ML-17395' 'JC-15385' 'JG-15160' 'MC-17275' 'NW-18400' 'TB-21280'
 'BS-11380' 'HH-15010' 'CD-12280' 'TH-21100' 'MM-18055' 'NS-18505'
 'RB-19645' 'SW-20455' 'EB-13930' 'PS-18760' 'HF-14995' 'HZ-14950'
 'CD-12790' 'JK-15205' 'FM-14215' 'ED-13885' 'DA-13450' 'JW-15955'
 'RM-19375' 'ML-17755' 'CC-12685' 'JE-15610' 'RP-19855' 'TB-21175'
 'BE-11455' 'JF-15565' 'PB-19210' 'BT-11680' 'JL-15235' 'CH-12070'
 'ND-18460' 'BF-10975' 'KH-16330' 'GW-14605' 'NC-18625' 'ME-18010'
 'BP-11230' 'JC-15775' 'AS-10090' 'AC-10450' 'MD-17860' 'DB-13660'
 'EH-13990' 'EH-13765' 'SC-20230' 'JE-15715' 'AC-10615' 'JD-16015'
 'CB-12415' 'JS-16030' 'LW-17215' 'SC-20800' 'AM-10705' 'RH-19510'
 'CT-11995' 'MC-17590' 'CC-12610' 'KA-16525' 'TC-20980' 'BF-11080'
 'MM-17260' 'AH-10120' 'BW-11200' 'SW-20245' 'BS-11665' 'RF-19345'
 'WB-21850' 'TB-21625' 'AF-10870' 'RB-19435' 'KF-16285' 'JH-15820'
 'IL-15100' 'PB-18805' 'RH-19600' 'AW-10930' 'ML-17410' 'DB-13555'
 'MH-17620' 'DK-13375' 'BT-11440' 'DB-13405' 'TG-21310' 'BF-11005'
 'JM-16195' 'MZ-17335' 'MW-18220' 'MV-17485' 'SM-20320' 'TP-21415'
 'JK-15625' 'PJ-18835' 'RS-19420' 'SV-20935' 'BC-11125' 'EM-13825'
 'BM-11575' 'KN-16705' 'KW-16570' 'SC-20260' 'CV-12295' 'SG-20605'
 'TM-21010' 'EM-13810' 'ML-18040' 'CR-12580' 'AZ-10750' 'PW-19240'
 'SC-20380' 'CM-11935' 'GM-14695' 'TB-21250' 'JM-15865' 'SC-20575'
 'LS-17200' 'RR-19315' 'DB-12910' 'TT-21220' 'LO-17170' 'KD-16615'
 'NB-18580' 'BD-11635' 'CM-12235' 'EN-13780' 'KN-16450' 'BO-11350'
 'AG-10300' 'MC-17635' 'TA-21385' 'JF-15295' 'TT-21265' 'SB-20170'
 'CL-12700' 'HG-15025' 'NL-18310' 'RR-19525' 'TC-21295' 'SV-20785'
 'BE-11410' 'SC-20680' 'DF-13135' 'FH-14350' 'MS-17530' 'RH-19555'
 'GA-14515' 'JP-16135' 'Dp-13240' 'MO-17950' 'DL-13330' 'MH-18025'
 'DR-12940' 'DM-13015' 'CA-11965' 'AC-10660' 'DM-13345' 'VF-21715'
 'CC-12370' 'BF-11275' 'HG-14845' 'BP-11155' 'EM-14140' 'MA-17995'
 'AY-10555' 'GB-14575' 'JB-16045' 'MG-17875' 'SR-20425' 'JB-16000'
 'DM-12955' 'TC-21475' 'SW-20350' 'RE-19450' 'BF-11215' 'KB-16405'
 'JG-15310' 'EC-14050' 'EB-14110' 'JP-15460' 'CS-11845' 'GH-14410'
 'PT-19090' 'JL-15130' 'AH-10030' 'CC-12475' 'DW-13195' 'SJ-20215'
 'BG-11740' 'LB-16795' 'CM-11815' 'EH-14185' 'TS-21505' 'PR-18880'
 'LC-17050' 'CS-12490' 'DH-13075' 'JO-15145' 'AH-10690' 'HJ-14875'
 'MH-17455' 'RD-19930' 'SC-20020' 'SU-20665' 'FC-14335' 'RB-19330'
 'NC-18535' 'DB-12970' 'MF-17665' 'RM-19750' 'VM-21835' 'EJ-13720'
 'NC-18415' 'LS-17230' 'KE-16420' 'DH-13675' 'PF-19120' 'VT-21700'
 'MG-17695' 'SP-20920' 'CS-12175' 'DK-12895' 'KM-16660' 'AA-10645'
 'DD-13570' 'AH-10465' 'TP-21565' 'EK-13795' 'CR-12820' 'SG-20890'
 'AH-10585' 'NF-18475' 'BS-11365' 'SH-20635' 'RD-19720' 'AG-10330'
 'GR-14560' 'VS-21820' 'TM-21490' 'TS-21430' 'DB-13360' 'NR-18550'
 'CS-11860' 'MF-18250' 'LW-17125' 'AR-10345' 'KS-16300' 'AB-10015'
 'LR-17035' 'SS-20410' 'JM-15580' 'JK-15325' 'DM-13525' 'ML-18265'
 'MH-17290' 'FC-14245' 'TH-21115' 'JK-16090' 'SB-20185' 'BG-11035'
 'BW-11065' 'MG-18205' 'DO-13645' 'BP-11050' 'TS-21655' 'EM-14200'
 'AO-10810' 'MH-17440' 'SS-20515' 'LD-16855' 'VP-21760' 'TC-21145'
 'IM-15055' 'AR-10570' 'CM-12715' 'FW-14395' 'LC-16960' 'HE-14800'
 'BD-11560' 'HD-14785' 'CJ-11875' 'RS-19870' 'SC-20845' 'RE-19405'
 'SM-20905']
Customer Name : ['Claire Gute' 'Darrin Van Huff' "Sean O'Donnell" 'Brosina Hoffman'
 'Andrew Allen' 'Irene Maddox' 'Harold Pawlan' 'Pete Kriz'
 'Alejandro Grove' 'Zuschuss Donatelli' 'Ken Black' 'Sandra Flanagan'
 'Emily Burns' 'Eric Hoffmann' 'Tracy Blumstein' 'Matt Abelman'
 'Gene Hale' 'Steve Nguyen' 'Linda Cazamias' 'Ruben Ausman' 'Erin Smith'
 'Odella Nelson' "Patrick O'Donnell" 'Lena Hernandez' 'Darren Powers'
 'Janet Molinari' 'Ted Butterfield' 'Kunst Miller' 'Paul Stevenson'
 'Brendan Sweed' 'Karen Daniels' 'Henry MacAllister' 'Joel Eaton'
 'Ken Brennan' 'Stewart Carmichael' 'Duane Noonan' 'Julie Creighton'
 'Christopher Schild' 'Paul Gonzalez' 'Gary Mitchum' 'Jim Sink'
 'Karl Braun' 'Roger Barcio' 'Parhena Norris' 'Katherine Ducich'
 'Elpida Rittenbach' 'Rick Bensley' 'Gary Zandusky' 'Lena Cacioppo'
 'Janet Martin' 'Pete Armstrong' 'Cynthia Voltz' 'Clay Ludtke'
 'Ryan Crowe' 'Dave Kipp' 'Greg Guthrie' 'Steven Cartwright'
 'Alan Dominguez' 'Philip Fox' 'Troy Staebel' 'Lindsay Shagiari'
 'Dorothy Wardle' 'Lena Creighton' 'Jonathan Doherty' 'Sally Hughsby'
 'Sandra Glassco' 'Helen Andreada' 'Maureen Gastineau' 'Justin Ellison'
 'Tamara Willingham' 'Stephanie Phelps' 'Neil Knudson' 'Dave Brooks'
 'Nora Paige' 'Ted Trevino' 'Eric Murdock' 'Ruben Dartt' 'Max Jones'
 'Becky Martin' 'Chad Sievert' 'Jennifer Braxton' 'Shirley Jackson'
 'Jim Kriz' 'David Kendrick' 'Robert Marley' 'Sally Knutson'
 'Frank Merwin' 'Alice McCarthy' 'Mark Packer' 'Mary Zewe'
 'Cassandra Brandow' 'Valerie Mitchum' 'Fred Hopkins' 'Maria Bertelson'
 'Bruce Stewart' 'Logan Currie' 'Heather Kirkland' 'Laurel Elliston'
 'Joseph Holt' 'Michael Stewart' 'Victoria Wilson' 'Jonathan Howell'
 'Joni Blumstein' 'David Smith' 'Valerie Dominguez' 'Erin Ashbrook'
 'David Bremer' 'Ken Lonsdale' 'Dianna Wilson' 'Logan Haushalter'
 'Kelly Collister' 'Delfina Latchford' 'Dan Reichenbach' 'Craig Carreira'
 'Dorris liebe' 'Sean Braxton' 'Roy Collins' 'Alan Hwang'
 'Claudia Bergmann' 'Christine Abelman' 'Kristen Hastings'
 'Barry Blumstein' 'Andrew Gjertsen' "Jas O'Carroll" 'Alan Haines'
 'Nick Zandusky' 'Kelly Lampkin' 'Alan Schoenberger' 'Corey Roper'
 'Shahid Hopkins' 'Ben Peterman' 'Thomas Seio' 'Andy Gerbode' 'Sung Pak'
 'Nathan Mautz' 'Frank Atkinson' 'Grace Kelly' 'Don Jones'
 "Patrick O'Brill" 'John Lucas' 'Doug Bickford' 'Alyssa Crouse'
 'Clay Cheatham' 'Tamara Dahlen' 'Adam Bellavance' 'Jeremy Lonsdale'
 'Victoria Brennan' 'Katrina Willman' 'Julia Dunbar' 'Michael Kennedy'
 'Guy Thornton' 'Arthur Gainer' 'Muhammed MacIntyre' 'Allen Rosenblatt'
 'Russell Applegate' 'Alejandro Savely' 'Laura Armstrong' 'Denny Ordway'
 'Dean Katz' 'Nathan Gelder' 'Mike Vittorini' 'Jack Garza' 'Bart Pistole'
 'Victor Preis' 'Saphhira Shifley' 'Anna Gayman' 'Luke Foster'
 'Roy FranzÃ¶sisch' 'Keith Herrera' 'Kimberly Carter' 'Caroline Jumper'
 'Philip Brown' 'Michael Paige' 'Natalie Fritzler' 'Shirley Daniels'
 'Ken Heidel' 'Ross Baird' 'Mike Kennedy' 'Philisse Overcash'
 'Brenda Bowman' 'Troy Blackwell' 'Raymond Buch' 'Ed Braxton'
 'Sanjit Chand' 'Tanja Norvell' 'Joni Sundaresam' 'Maya Herman'
 'Jeremy Pistek' 'Jeremy Ellison' 'John Grady' 'Xylona Preis' 'Erin Mull'
 'Michelle Tran' 'Sue Ann Reed' 'Carl Weiss' 'Astrea Jones' 'Sonia Sunley'
 "Rose O'Brian" 'Maribeth Dona' 'Maribeth Yedwab' 'Christopher Martinez'
 'Lynn Smith' 'Bradley Nguyen' 'Dean Braden' 'Matt Connell' 'Brian Dahlen'
 'Patricia Hirasaki' 'Mike Gockenbach' 'Karen Bern' 'Jasper Cacioppo'
 'Rob Lucas' 'Allen Armold' 'Emily Phan' 'Darren Koutras'
 'Bradley Drucker' 'Liz MacKendrick' 'Adrian Shami' 'Bill Donatelli'
 'Greg Tran' 'Ashley Jarboe' 'Olvera Toch' 'Liz Pelletier'
 'Cynthia Arntzen' 'Jeremy Farry' 'Frank Preis' 'Ellis Ballard'
 'Jennifer Ferguson' 'Sarah Foster' 'Trudy Glocke' 'Carlos Soltero'
 'Charles Crestani' 'Dianna Vittorini' 'Bruce Degenhardt'
 'Zuschuss Carroll' 'Melanie Seite' 'Lena Radford' 'Theone Pippenger'
 'Chloris Kastensmidt' 'Alan Shonely' 'Andrew Roberts' 'Nona Balk'
 'Giulietta Dortch' 'Clytie Kelty' 'Nat Gilpin' 'Christina Anderson'
 'Sylvia Foulston' "Meg O'Connel" 'Annie Thurman' 'Fred McMath'
 'Denny Joy' 'Max Engle' 'Justin Deggeller' 'John Lee' 'Sean Christensen'
 'Chuck Clark' 'Anthony Rawles' 'Steven Roelle' 'Craig Reiter'
 'Eugene Hildebrand' 'Sibella Parks' 'Tiffany House' 'Resi PÃ¶lking'
 'Rob Beeghly' 'Carol Darley' 'Doug Jacobs' 'Grant Thornton'
 'Michael Chen' 'Ralph Arnett' 'Naresj Patel' 'Alan Barnes' 'Jesus Ocampo'
 'Jay Kimmel' 'Brad Norvell' 'David Philippe' 'Tracy Hopkins'
 'Arthur Prichep' 'Roland Schwarz' 'Seth Vernon' 'Christine Kargatis'
 'Ross DeVincentis' 'Mathew Reese' 'Steve Chapman' 'Jay Fein'
 'Emily Grady' 'Darrin Sayre' 'Phillina Ober' 'Sung Shariari'
 'Peter BÃ¼hler' 'Roland Fjeld' 'Yoseph Carroll' 'Debra Catini'
 'Christine Phan' 'Barry FranzÃ¶sisch' 'Lisa Hazard' 'Chris Selesnick'
 'Anthony Johnson' 'Benjamin Venier' 'Dan Lawera' 'Bryan Mills'
 'Liz Thompson' 'Joe Kamberova' 'Erica Smith' 'Rick Hansen' 'Carlos Daly'
 'Helen Wasserman' 'Mike Caudle' 'Gary McGarr' 'Pauline Johnson'
 'Bart Watters' 'Toby Ritter' 'Patrick Gardner' 'James Lanier'
 'Brian Moss' 'Eudokia Martin' 'Art Foster' 'Guy Armstrong' 'Cyma Kinney'
 'Dave Poirier' 'Berenike Kampe' 'Sanjit Jacobs' 'Chuck Magee'
 'Anthony Jacobs' 'Linda Southworth' 'Guy Phonely' 'Paul Knutson'
 'Sally Matthias' 'Anthony Garverick' 'Peter McVee' 'Lauren Leatherbury'
 'Jill Stevenson' 'Ed Ludwig' 'Pamela Coakley' 'Hunter Lopez'
 'Maribeth Schnelling' 'George Bell' 'Justin Ritter' 'Bill Eplett'
 'Sample Company A' 'Rob Williams' 'Sanjit Engle' 'Adam Hart'
 'Jessica Myrick' 'Joel Jenkins' 'Ralph Kennedy' 'Catherine Glotzbach'
 'Rachel Payne' 'Karen Carlisle' 'Katherine Hughes' 'Greg Hansen'
 'Scott Williamson' 'Joseph Airdo' 'Daniel Lacy' 'Lindsay Williams'
 'Thomas Brumley' 'Bryan Spruell' 'Robert Waldorf' 'Tracy Zic'
 'Ann Steele' 'Toby Swindell' 'Sara Luxemburg' 'Mitch Willingham'
 'Rob Dowd' 'Ryan Akin' 'Meg Tillman' 'Vivek Gonzalez' 'John Stevenson'
 'Kalyca Meade' 'Hallie Redmond' 'Deanra Eno' 'Allen Goldenen'
 'Jennifer Jackson' 'Jennifer Halladay' 'Robert Dilbeck' "Mary O'Rourke"
 'Noel Staavos' 'Deirdre Greer' 'Nicole Fjeld' 'Matthew Grinstein'
 'Theresa Swint' 'Brian DeCherney' 'Charles McCrossin' 'Skye Norling'
 'Erica Hernandez' 'Frank Olsen' 'Maurice Satty' 'Chad Cunningham'
 'Don Weiss' 'Bill Tyler' 'Craig Yedwab' 'Brad Thomas' 'Penelope Sewall'
 'Paul Van Hugh' 'Neoma Murray' 'Dionis Lloyd' 'Christine Sundaresam'
 'Frank Hawley' 'Nat Carroll' 'Alex Avila' 'Larry Tron' 'Anne Pryor'
 'Paul MacIntyre' 'Alyssa Tate' 'Cathy Armstrong' 'Harold Ryan'
 'Bradley Talbott' 'Larry Hughes' 'Steven Ward' 'Stefania Perrino'
 'Ben Ferrer' 'Kean Thornton' 'Brooke Gillingham' 'Greg Matthias'
 'Eva Jacobs' 'Nora Preis' 'Mick Hernandez' 'Jocasta Rupert'
 'Suzanne McNair' 'Chris Cortes' 'Phillip Flathmann' 'Dan Campbell'
 'Bryan Davis' 'Gene McClure' 'Todd Boyes' 'Justin Hirsh' 'Erica Bern'
 'Quincy Jones' 'Tracy Collins' 'Chuck Sachs' 'Henry Goldwyn'
 'Laurel Workman' 'Matt Collins' 'Liz Preis' 'Evan Bailliet'
 'George Zrebassa' 'Cathy Prescott' 'Frank Gastineau' 'Lisa DeCherney'
 'Alejandro Ballentine' 'Michael Nguyen' 'Jim Radford' 'Jamie Frazer'
 'Chad McGuire' 'Aaron Smayling' 'Beth Paige' 'Natalie DeCherney'
 'Larry Blacks' 'Kean Takahito' 'Harry Marie' 'Ann Blume' 'Sam Zeldin'
 'Michael Granlund' 'Julie Kriz' 'Paul Prost' 'Yana Sorensen'
 'Katherine Murray' 'Adrian Barton' 'Helen Abelman' 'Beth Thompson'
 'Stuart Van' 'Rick Wilson' 'Damala Kotsonis' 'Shui Tom' 'Michael Moore'
 'Pauline Webber' 'Shaun Chance' 'Thais Sissman' 'Mark Cousins'
 'Maria Etezadi' 'Nicole Hansen' 'Mick Brown' 'Keith Dawkins'
 'Katherine Nockton' 'Nora Pelletier' 'Cindy Stewart' 'Maxwell Schwartz'
 'Corinna Mitchell' 'Corey-Lock' 'Todd Sumrall' 'Jane Waco' 'John Dryer'
 'Pauline Chand' 'Andy Reiter' 'Arianne Irving' 'Tom Boeckenhauer'
 'Paul Lucas' 'Gary Hwang' 'Mike Pelletier' 'Jim Mitchum' 'Carl Ludwig'
 'Deborah Brumfield' 'Ivan Gibson' 'Bobby Odegard' 'Aimee Bixby'
 'Julia West' 'Edward Becker' 'Sheri Gordon' 'Charlotte Melton'
 'Anthony Witt' 'Mick Crebagga' 'Tonja Turnell' 'Vivek Grady'
 'Muhammed Yedwab' 'Rick Duston' 'Dennis Pardue' 'Marina Lichtenstein'
 'Jenna Caffey' 'James Galang' 'Marc Crier' 'Natalie Webber'
 'Toby Braunhardt' 'Bill Stewart' 'Hilary Holden' 'Christina DeMoss'
 'Thea Hendricks' 'Michelle Moray' 'Neola Schneider' 'Robert Barroso'
 'Shaun Weien' 'Eric Barreto' 'Pamela Stobb' 'Herbert Flentye'
 'Henia Zydlo' 'Cynthia Delaney' 'Jamie Kunitz' 'Filia McAdams'
 'Emily Ducich' 'Dianna Arnett' 'Joni Wasserman' 'Raymond Messe'
 'Max Ludwig' 'Craig Carroll' 'Jim Epp' 'Roy Phan' 'Thomas Boland'
 'Brad Eason' 'Jill Fjeld' 'Phillip Breyer' 'Brian Thompson' 'Janet Lee'
 'Cathy Hwang' 'Neil Ducich' 'Barbara Fisher' 'Katharine Harms'
 'Giulietta Weimer' 'Noah Childs' 'Michelle Ellison' 'Benjamin Patterson'
 'John Castell' 'Adam Shillingsburg' 'Amy Cox' 'Michael Dominguez'
 'Duane Benoit' 'Erica Hackney' 'Edward Hooks' 'Scot Coram' 'Joe Elijah'
 'Ann Chong' 'Joy Daniels' 'Christy Brittain' 'Joy Smith' 'Luke Weiss'
 'Stuart Calhoun' 'Anne McFarland' 'Rick Huthwaite' 'Carol Triggs'
 'Matt Collister' 'Corey Catlett' 'Kelly Andreada' 'Tamara Chand'
 'Bart Folk' 'Magdelene Morse' 'Adrian Hane' 'Ben Wallace' 'Scot Wooten'
 'Brian Stugart' 'Randy Ferguson' 'William Brown' 'Trudy Brown'
 'Art Ferguson' 'Richard Bierner' 'Karen Ferguson' 'John Huston'
 'Ivan Liston' 'Patrick Bzostek' 'Rob Haberlin' 'Arthur Wiediger'
 'Maris LaWare' 'Dorothy Badders' 'Matt Hagelstein' 'Dennis Kane'
 'Bobby Trafton' 'Denny Blanton' 'Toby Gnade' 'Barry Franz'
 'Justin MacKendrick' 'Maria Zettner' 'Mitch Webber' 'Mark Van Huff'
 'Sean Miller' 'Tom Prescott' 'Jim Karlsson' 'Patrick Jones'
 'Ricardo Sperren' 'Susan Vittorini' 'Becky Castell' 'Elizabeth Moffitt'